language: elixir
elixir:
  - 1.2.6
  - 1.3.1
  - 1.6.6
otp_release:
  - 17.5
  - 18.2.1
  - 20.3.8.2
matrix:
  exclude:
    - elixir: 1.2.6
      otp_release: 17.5
    - elixir: 1.3.1
      otp_release: 17.5
    - elixir: 1.2.6
      otp_release: 20.3.8.2
    - elixir: 1.3.1
      otp_release: 20.3.8.2
    - elixir: 1.6.6
      otp_release: 18.2.1
    - elixir: 1.6.6
      otp_release: 17.5
sudo: false # to use faster container based build environment
script:
  - mix test

